on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: "Login to Docker Hub"
        run: docker login --username ${{ secrets.doker_token}} --password ${{ secrets.dckr_pat_84jEi7IoPm6f9AG-6UjVtXtGLbY }}

      - name: "Building docker image"
        run: docker build -t ${{ secrets.docker_token }}/my_name .

      - name: "Pushing to Docker Hub"
        run: docker push ${{ secrets.docker_token}}/my_name
